#!/bin/bash

set -e

# Needed for the mock code to work
pip install pytest

# Install the plugin explicity
pip install -e ./

# Neet to use an updated version of aiida-core
pip install --force-reinstall git+https://github.com/zhubonan/aiida-core.git@0531a6eb8ccd65003b58fad790aa72a59bcce72e
