name: ci

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Cache python dependencies
        id: cache-pip
        uses: actions/cache@v4.0.2
        with:
          path: ~/.cache/pip
          key: pip-${{ matrix.python }}-tests-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: pip-${{ matrix.python }}-tests-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install parsevasp
        run: pip install -e ."[tests]" -vvv

      - name: Run tests with codecov
        run: pytest --cov=aiida_vasp --cov-append --cov-report=xml --cov-report=term-missing -k 'not converge_wc'

      - name: Archive error mock calculations
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: error-mock-calc-archive
          path: |
            test_mock_error.aiida
          retention-days: 5
          if-no-files-found: warn

      - name: Upload coverage to Codecov
        if: matrix.python == '3.12'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: aiida-vasp
          flags: pytests
          fail_ci_if_error: true
